### ISSUE TITLE
Improvements on Buttons

### ISSUE THREAD

**Issue by raffaellar** [alfio-event/alf.io-public-frontend#10]
- [x] Move from Outline to Button Light 
- [x] On mobile homepage - Continue should be displayed before Back to the website, currently:
<img width="551" alt="Screenshot 2019-07-21 at 16 15 32" src="https://user-images.githubusercontent.com/44751791/61592398-06150200-abd3-11e9-9ee1-e048d8830bf6.png">

- [x] On mobile - the same on the following page, invert Cancel and Continue
- [x] On mobile - the same on the following page, invert Back to event site and Download your invoice
- [x] On mobile - space out Back to event site and Download your invoice

**Comment by syjer** [comment]
note: https://github.com/alfio-event/alf.io-public-frontend/commit/c7b109c850d22c5f9a73ce5cabac292c6711d123 is referencing this issue, not #20 ...

**Comment by syjer** [comment]
done
