### ISSUE TITLE
Virus detected 

### ISSUE THREAD

**Issue by adrianleul** [alfio-event/alf.io-public-frontend#123]
When I tried to download the zip file but it was stopped by Windows Defender
![vir](https://github.com/user-attachments/assets/cee9fd16-660b-4925-afc6-c56b467f7095)

**Comment by syjer** [comment]
hi @addydumb , we are quite sure it's a false positive, anyway, this repository is deprecated, the frontend is now directly integrated in the main one: https://github.com/alfio-event/alf.io
