### ISSUE TITLE
Missing error feedback on update ticket

### ISSUE THREAD

**Issue by cbellone** [alfio-event/alf.io-public-frontend#19]
How to reproduce:

- complete a reservation
- add a new additional information, and mark it as required
- open the reservation page, try to update the ticket
![image](https://user-images.githubusercontent.com/3385346/62772989-46b0be80-baa1-11e9-8812-6b0f775cae7e.png)
- the PUT call produces an error response, which is not displayed by the application
![image](https://user-images.githubusercontent.com/3385346/62773053-765fc680-baa1-11e9-8cfe-0275e99d635d.png)

**Comment by syjer** [comment]
fixed :D
