### ISSUE TITLE
support subscriptions

### ISSUE THREAD

**Issue by syjer** [alfio-event/alf.io-public-frontend#55]
The event list page will be changed in the following way: 2 sections.

First section "Events" with: up to next 4 events. If more -> display a "more" button.
Second section: "Subscriptions" with: up to 4 subscriptions. If more -> display a "more" button.

Create a new list all events page which is linked by the more button. -> display paginated 20 events(client side)  + client side search
Create a new list all subscription page  which is linked by the more button.

More compact event view.

We can also add the support of tags for filtering for events.

**Comment by cbellone** [comment]
implemented! :+1:
